create table person(
                       person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(100) unique,
                       year_birthday int
);

create table book(
                     book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name varchar(100),
                     author varchar(100),
                     year int,
                     id_person int references person(person_id) ON DELETE SET NULL,
                     data_issue date
);